### ISSUE TITLE
如何将快速将Docbook文档转换为po格式？

### ISSUE THREAD

**Issue by ghost** [cwlin0416/freebsd-handbook#5]
想问问您当时是如何实现的？

**Comment by cwlin0416** [comment]
Hi @ccc1924 
由於 Docbook 的格式與 PO 檔格式的內容有一段差距 (PO 檔為最新版本)，所以是沒有辦法直接用轉換的，全部由人工對照把還能夠採用的部份手動移到 PO 檔

**Comment by ghost** [comment]
好吧
谢谢回复
